language: c
os:
 - linux
 - osx
sudo: false
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - clang
    - valgrind

env:
# - MYCC=gcc-5   BUILD_TYPE=Release
 - MYCC=gcc-5   BUILD_TYPE=Debug
 - MYCC=clang   BUILD_TYPE=Release
# - MYCC=clang   BUILD_TYPE=Debug

matrix:
  exclude:
    - os: osx
      env: MYCC=gcc-5   BUILD_TYPE=Release
    - os: osx
      env: MYCC=gcc-5   BUILD_TYPE=Debug

script:
 - mkdir build
 - cd build
 - CC=$MYCC cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE || exit 1
 - cmake --build . -- -j2 || exit 1
 - cd tests
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
     ./tests || exit 1;
   else
     valgrind --error-exitcode=42 --leak-check=full ./tests || exit 1;
   fi

